In [3]:
import numpy as np
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [4]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
g=[0,2,4]
a[g]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [6]:
np.mean(a[g], axis = 0)

array([12., 13., 14., 15., 16., 17.])

In [7]:
g=[0,1,2,0,3]
a[g]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a = np.arange(5)
a*a

array([ 0,  1,  4,  9, 16])

In [9]:
np.sum(a*a)**0.5

5.477225575051661